services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Porta para comunicação usa o TCP/IP
      - "15672:15672" # Interface gráfica
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" #Interface gráfica
      - "6831:6831/udp" #Traces
      - "14268:14268" # Traces http
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP
  api-gateway:
    image: kong:3.9
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_DECLARATIVE_CONFIG: "/kong/config.yaml"
    extra_hosts: # expõe as rotas dos outros serviços (Ele vai ver o localhost como o localhost dele)
      - "host.docker.internal:host-gateway"
    volumes:
      - "./docker/kong/config.yaml:/kong/config.yaml"
    ports:
      - "8000:8000" # PROXY API
      - "8001:8001" # API ADMIN
      - "8002:8002" # UI ADMIN
      - "8443:8443" # PROXY SSL HTTPS
      - "8444:8444" # API ADMIN SSL HTTPS

volumes:
  rabbitmq_data:
